POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2NjNhYThhZGEwZmMxMTRiODY0NTRmZTEiLCJpYXQiOjE3MTUxMjA0MDYsImV4cCI6MTcxNzcxMjQwNn0.1iXtOyitCcTGhJItFOZ9rb4Mewi15aVvd4WadSF4aBw

{
"url": "www.jee.fi",
"title": "TESTI BLOGI 2",
"author": "toimi",
"userID": "663aa8f5a0fc114b86454fe4",
"likes": 110
}