POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxpc8OkeXMiLCJpZCI6IjY2MWU3OGM1YzUyNjM5ZmQ4Mzk5ZTk2MSIsImlhdCI6MTcxMzI3MzE2Nn0.lCKdnPB43ZHCLI7wrAcPDfGeP5Yh64DqcU5KejTaD5U

{
"url": "www.jee.fi",
"title": "TOIMIIKO HÄ",
"author": "jeejee",
"userID": "661e78c5c52639fd8399e961",
"likes": 0
}